import { existsSync, rmSync } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';

import HtmlWritable from './html-writable.js';

const copyDir = async (src, dest) => {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    const isDirectory = entry.isDirectory();

    if (isDirectory) {
      await copyDir(srcPath, destPath);
    } else {
      await fs.copyFile(srcPath, destPath);
    }
  }
};

const isExists = async (path) => {
  try {
    await fs.access(path);
    return true;
  } catch {
    return false;
  }
};

const writeFile = async (filePath, data) => {
  try {
    const dirname = path.dirname(filePath);
    const exist = await isExists(dirname);
    if (!exist) {
      await fs.mkdir(dirname, { recursive: true });
    }

    await fs.writeFile(filePath, data, 'utf8');
  } catch (err) {
    throw new Error(err);
  }
};

const toAbsolute = (p) => path.resolve(__dirname, p);

let didError = false;

console.log('Generating static site...');

if (!existsSync(toAbsolute('build/server/entry-server.js'))) {
  throw new Error('Server build exists');
}

const ssrManifest = JSON.parse(
  await fs.readFile(toAbsolute('build/client/.vite/ssr-manifest.json'), 'utf-8'),
);
const template = await fs.readFile(toAbsolute('build/client/index.html'), 'utf-8');
// @ts-expect-error - this file is generated by Vite may not exist, we handle this case before.
const { render } = await import('./build/server/entry-server.js');
const { allPosts } = await import('./src/mdx/index.ts');
const { ENV_CANONICAL_URL } = await import('./src/constants/app.ts');
const routesToPrerender = ['/', ...allPosts.map((p) => p.path)];
const routesMetadata = allPosts.reduce(
  (acc, post) => {
    acc[post.path] = {
      title: post.title,
      description: post.description,
    };
    return acc;
  },
  {
    '/': {
      title: 'm-sixteen, paris punk rock, 2000-2010',
      description:
        "A trifling story drawn upon the 90's Punk Rock revival's teenage fantasy to his inevitable forfeit.",
    },
  },
);

if (existsSync(toAbsolute('dist'))) {
  console.log('Removing existing dist directory...');
  rmSync(toAbsolute('dist'), { recursive: true });
}

console.log('Copying public directory into fresh dist directory...');
await copyDir(toAbsolute('public'), toAbsolute('dist'));
console.log('Copying build/client/assets directory into dist/assets...');
await copyDir(toAbsolute('build/client/assets'), toAbsolute('dist/assets'));

console.log('Pre-rendering routes...');
// TODO: Use Promise to handle async file writes
for (const url of routesToPrerender) {
  if (didError) {
    break;
  }
  const writable = new HtmlWritable();

  writable.on('finish', async () => {
    const [htmlStart, htmlEnd] = template.split(`<!--app-html-->`);
    const canonicalUrl = `${ENV_CANONICAL_URL}${url}`;
    const { title, description } = routesMetadata[url];
    const html = [htmlStart, writable.getHtml(), htmlEnd].join('').replace(
      `    <link rel="canonical" href="https://m-sixteen.com/" />
    <meta name="description" content="A trifling story drawn upon the 90's Punk Rock revival's teenage fantasy to his inevitable forfeit." />
    <title>m-sixteen, paris punk rock, 2000-2010</title>`,
      `    <link rel="canonical" href="${canonicalUrl}" />
    <meta name="description" content="${description}" />
    <title>${title}</title>`,
    );

    // Each route is written to dist/<route>/index.html to handle extention less URLs
    // e.g. https://m-sixteen.com/early-years/eragny
    // TODO: make sure this is the correct way to handle this on GH pages
    const filePath = `dist${url === '/' ? '' : url}/index.html`;
    await writeFile(toAbsolute(filePath), html);
    console.log(`Wrote ${filePath}`);
  });

  const { pipe } = render(url, ssrManifest, {
    onAllReady() {
      pipe(writable);
    },
    onError(error) {
      didError = true;
      console.error('Failed to pre-render routes');
      console.error(error);
      process.exit(1);
    },
  });
}
