import type { ConcertProps } from '@/types/model';

/*
  In order to save space and normalize as much as possible the data,
  we should do the following:
  - [ ] create a `countries` and `cities` dictionaries to avoid repeating the same long strings
  - [ ] store dates as a string in the format 'YYYY-MM-DD' rather than an array
 */

const formatEventMonth = new Intl.DateTimeFormat('en', { month: 'short' });

const concertsRaw: Omit<ConcertProps, 'monthString' | 'dayString' | 'dateIso' | 'kind'>[] = [
  {
    date: ['2000', '6', '3'],
    venue: 'Locaux Larsen',
    city: 'Chambery',
    country: 'France',
    bands: ['Pamela', 'Softworld'],
  },
  {
    date: ['2000', '6', '21'],
    venue: 'Fête de la musique',
    city: "L'Isle adam",
    country: 'France',
    bands: ['The Marxmallows'],
  },
  {
    date: ['2001', '6', '2'],
    venue: "Maison de l'Isle adam",
    city: "L'Isle adam",
    country: 'France',
    bands: ['Flying Pooh', 'The Marxmallows', 'Day Off'],
  },
  {
    date: ['2001', '6', '21'],
    venue: 'Fête de la musique',
    city: "L'Isle adam",
    country: 'France',
    bands: ['The Marxmallows', 'Day Off', 'Softworld'],
  },
  {
    date: ['2001', '6', '22'],
    venue: 'Back to your roots fest',
    city: 'Parmain',
    country: 'France',
    bands: ['The Marxmallows', 'Day Off', 'Strike Back', 'NHC'],
  },
  {
    date: ['2002', '1', '28'],
    venue: 'Péniche blues café',
    city: 'Paris',
    country: 'France',
    bands: ["Wake n' Bake", 'Sagabronx', 'Taste it', '36 Fist'],
  },
  {
    date: ['2002', '2', '15'],
    venue: 'House show',
    city: 'Pontoise',
    country: 'France',
    bands: ['The Marxmallows', 'Day Off', 'Strike Back', 'NHC', 'Full Screen'],
  },
  {
    date: ['2002', '5', '2'],
    venue: 'Péniche blues café',
    city: 'Paris',
    country: 'France',
    bands: ['5 days off', 'Six rich dead', 'Off your head'],
  },
  {
    date: ['2002', '5', '15'],
    venue: 'Café de la fac',
    city: 'Compiègne',
    country: 'France',
    bands: [],
  },
  {
    date: ['2002', '5', '25'],
    venue: 'La mezzanine',
    city: 'Pierrelaye',
    country: 'France',
    bands: ['Strike Back', 'Insula'],
  },
  {
    date: ['2002', '4', '6'],
    venue: 'La Javanaise',
    city: 'Meaux',
    country: 'France',
    bands: ['The Marxmallows'],
  },
  {
    date: ['2002', '6', '8'],
    venue: 'Festival rock',
    city: 'Auvers sur oise',
    country: 'France',
    bands: ['Lagony', 'Wunjo', 'NSVF', 'Sismix dub'],
  },
  {
    date: ['2002', '6', '21'],
    venue: 'Place Jean Taris',
    city: 'Paris',
    country: 'France',
    bands: ['Softworld', 'The Marxmallows', 'Hogwash', 'Sagabronx', 'Lumpy'],
  },
  {
    date: ['2002', '10', '12'],
    venue: "Studio de l'usine",
    city: 'Eragny',
    country: 'France',
    bands: ['Undeclinable', 'Full Screen'],
  },
  {
    date: ['2003', '3', '7'],
    venue: 'La frat',
    city: 'Arcueil',
    country: 'France',
    bands: ['Eths', 'The arss', 'Peach from the lair', 'Bawdy festival'],
  },
  {
    date: ['2003', '4', '6'],
    venue: 'Le café montmartre',
    city: 'Paris',
    country: 'France',
    bands: ['Daria', 'Full Screen', 'Thirty Six Side'],
  },
  {
    date: ['2003', '4', '17'],
    venue: 'Tapas la movida',
    city: 'Nice',
    country: 'France',
    bands: ['Pink ponk'],
  },
  {
    date: ['2003', '4', '18'],
    venue: 'Fort de la coudoullière',
    tour: 'NTM tour',
    city: 'Toulon',
    country: 'France',
    bands: ['Superdumb', 'Matavan'],
  },
  {
    date: ['2003', '4', '19'],
    venue: 'La machine à coudre',
    tour: 'NTM tour',
    city: 'Marseille',
    country: 'France',
    bands: ['Fast4ward'],
  },
  {
    date: ['2003', '4', '26'],
    venue: '95 district festival',
    tour: 'NTM tour',
    city: 'Pontoise',
    country: 'France',
    bands: [
      'The Marxmallows',
      'Strike Back',
      'Full Screen',
      'NHC',
      "Burst one's side",
      'Side effect',
    ],
  },
  {
    date: ['2003', '6', '20'],
    venue: 'Lycée Massillon',
    city: 'Paris',
    country: 'France',
    bands: ['Full up'],
  },
  {
    date: ['2003', '6', '21'],
    venue: 'Place Sully Morlan',
    city: 'Paris',
    country: 'France',
    bands: ['Hogwash', 'NHC', "Burst one's side", 'm-tripper', 'For a second', 'ozone', '4 ever'],
  },
  {
    date: ['2003', '11', '2'],
    venue: 'Phoenix club',
    city: 'Liège',
    country: 'Belgium',
    bands: [],
  },
  {
    date: ['2003', '11', '10'],
    venue: '95 district festival',
    city: 'Pontoise',
    country: 'France',
    bands: [
      'The Marxmallows',
      'Strike Back',
      'Full Screen',
      'NHC',
      "Burst one's side",
      'Side effect',
    ],
  },
  {
    date: ['2003', '12', '1'],
    venue: 'Péniche blues café',
    city: 'Paris',
    country: 'France',
    bands: ['Strike anywhere', 'NMDS', 'Strike Back'],
  },
  {
    date: ['2004', '1', '4'],
    venue: 'Café montmartre',
    city: 'Paris',
    country: 'France',
    bands: ['Actions fall short', "Burst one's side", 'manifest'],
  },
  {
    date: ['2004', '2', '13'],
    venue: 'Salle des fêtes',
    city: 'Pontoise',
    country: 'France',
    bands: ['Off your head', 'Thirty Six Side', 'Strike Back', 'Union Jack'],
  },
  {
    date: ['2004', '3', '13'],
    venue: 'Péniche alternat',
    city: 'Paris',
    country: 'France',
    bands: ['Sixtoys', 'Hogwash'],
  },
  {
    date: ['2004', '4', '17'],
    venue: 'Foyer municipal',
    city: 'Meulan',
    country: 'France',
    bands: ['Strike Back', 'NHC', 'X-eed'],
  },
  {
    date: ['2004', '5', '8'],
    venue: 'Showcase Fnac',
    city: 'Cergy',
    country: 'France',
    bands: [],
  },
  {
    date: ['2004', '5', '14'],
    venue: 'Salle des fêtes',
    city: 'Pontoise',
    country: 'France',
    bands: ['Union Jack', 'courir les rues', 'Logoré'],
  },
  {
    date: ['2004', '6', '11'],
    venue: 'Péniche alternat',
    city: 'Paris',
    country: 'France',
    bands: ['Shai-hulud', 'Draft', 'Last quiet time'],
  },
  {
    date: ['2004', '6', '20'],
    venue: 'Squat Alternation',
    city: 'Paris',
    country: 'France',
    bands: ['Metronome Charisma', 'Backsight'],
  },
  {
    date: ['2004', '6', '21'],
    venue: 'Stade charlemagne',
    city: 'Paris',
    country: 'France',
    bands: [
      "Burst one's side",
      'Side effect',
      'For a second',
      'Jetsex',
      'Actions fall short',
      'Dumb resolution',
      'm-tripper',
    ],
  },
  {
    date: ['2004', '6', '26'],
    venue: 'Furia sound festival',
    city: 'Taverny',
    country: 'France',
    bands: ['Zeke', 'Unsane', 'Ska-P', 'Svinkels', 'Cali', 'les Wampas'],
  },
  {
    date: ['2004', '9', '24'],
    venue: "Studios de l'usine",
    city: 'Eragny',
    country: 'France',
    bands: ['Union Jack', 'Minimum Serious'],
  },
  {
    date: ['2004', '8', '15'],
    venue: 'Péniche alternat',
    city: 'Paris',
    country: 'France',
    bands: ['Justice', 'Mental'],
  },
  {
    date: ['2004', '10', '3'],
    venue: 'Café montmartre',
    city: 'Paris',
    country: 'France',
    bands: ['Dumb resolution', 'Strike Back', 'NHC'],
  },
  {
    date: ['2004', '10', '15'],
    venue: 'Le Jokelson',
    tour: 'Hogsteen tour',
    city: 'Dunkerke',
    country: 'France',
    bands: ['Hogwash'],
  },
  {
    date: ['2004', '10', '16'],
    venue: 'La braise',
    tour: 'Hogsteen tour',
    city: 'Charlerois',
    country: 'Belgium',
    bands: ['Hogwash', 'Furious', 'Incriminate 77'],
  },
  {
    date: ['2004', '10', '24'],
    venue: 'Le duplex',
    tour: 'Hogsteen tour',
    city: 'Le Havre',
    country: 'France',
    bands: ['Hogwash'],
  },
  {
    date: ['2004', '10', '26'],
    venue: 'Le Gambetta',
    tour: 'Hogsteen tour',
    city: 'Paris',
    country: 'France',
    bands: ['Hogwash', 'Mel team plugs'],
  },
  {
    date: ['2004', '10', '29'],
    venue: 'Ama virtual club',
    tour: 'Hogsteen tour',
    city: 'Nyon',
    country: 'Switzerland',
    bands: ['Hogwash', 'Marplodz'],
  },
  {
    date: ['2004', '10', '30'],
    venue: "L'hotel de la musique",
    tour: 'Hogsteen tour',
    city: 'Marseille',
    country: 'France',
    bands: ['Hogwash', 'Day by Day'],
  },
  {
    date: ['2004', '10', '31'],
    venue: 'Le blue banana',
    tour: 'Hogsteen tour',
    city: 'Lyon',
    country: 'France',
    bands: ['Hogwash', 'Cortona'],
  },
  {
    date: ['2004', '11', '5'],
    venue: 'Le Zicodrome',
    city: 'Compiègne',
    country: 'France',
    bands: ['Sanitary Napkins'],
  },
  {
    date: ['2004', '11', '19'],
    venue: 'Le Forum',
    city: 'Vauréal',
    country: 'France',
    bands: ['Thirty Six Side', 'Strike Back'],
  },
  {
    date: ['2004', '11', '20'],
    venue: 'Le tigre',
    city: 'Selestat',
    country: 'France',
    bands: ['By my fist', 'The deafening noise'],
  },
  {
    date: ['2005', '1', '14'],
    venue: 'Bar la place',
    city: 'Caen',
    country: 'France',
    bands: ['Dumb resolution', 'Every second week'],
  },
  {
    date: ['2005', '1', '15'],
    venue: 'Le Napoleon',
    city: 'Tours',
    country: 'France',
    bands: ['Nine eleven', 'Get lost'],
  },
  {
    date: ['2005', '4', '16'],
    venue: '95 district festival',
    city: 'Pontoise',
    country: 'France',
    bands: [
      'The Marxmallows',
      'Strike Back',
      'Full Screen',
      'NHC',
      "Burst one's side",
      'Side effect',
      'the Ollie daze',
    ],
  },
  {
    date: ['2005', '4', '30'],
    venue: 'MJC',
    city: 'Plouarzel',
    country: 'France',
    bands: ['FTX', 'Bunkum', 'Youssouf Today'],
  },
  {
    date: ['2005', '5', '3'],
    venue: 'Magnet club',
    city: 'Berlin',
    country: 'Germany',
    bands: ['False Friend', 'Gest'],
  },
  {
    date: ['2005', '6', '19'],
    venue: 'Salle des fêtes',
    city: 'Meulan',
    country: 'France',
    bands: ['Strike Back', "Burst one's side", 'Chépa', 'Side effect'],
  },
  {
    date: ['2005', '10', '8'],
    venue: 'Free edge fest',
    city: 'Le Mans',
    country: 'France',
    bands: [
      'Nine eleven',
      'Sequoia',
      'Backsight',
      'Trouble everyday',
      'Aside from a day',
      'the elecktrocution',
    ],
  },
  {
    date: ['2005', '10', '26'],
    venue: "T'es rock coco",
    city: 'Angers',
    country: 'France',
    bands: ['The Marxmallows'],
  },
  {
    date: ['2005', '10', '27'],
    venue: 'Bar des artistes',
    city: 'Laval',
    country: 'France',
    bands: ['The Marxmallows', 'U-Skull'],
  },
  {
    date: ['2005', '11', '17'],
    venue: 'Le Batofar',
    city: 'Paris',
    country: 'France',
    bands: ['Antimaniax', 'Union Jack', 'ISP', 'the Pookis'],
  },
  {
    date: ['2006', '1', '20'],
    venue: 'Le Batofar',
    city: 'Paris',
    country: 'France',
    bands: ['Thirty Six Side', 'The Marxmallows', 'Strike Back'],
  },
  {
    date: ['2006', '3', '3'],
    venue: 'Les 18 marches',
    city: 'Moissy Crammayel',
    country: 'France',
    bands: ['Leptik Ficus', 'Dice curse'],
  },
  {
    date: ['2006', '10', '21'],
    venue: 'Le coliseum café',
    city: 'Charlerois',
    country: 'Belgium',
    bands: ['Hogwash', 'End over'],
  },
  {
    date: ['2006', '10', '28'],
    venue: 'Alternative festival',
    city: 'Villiers sur marne',
    country: 'France',
    bands: ['Burnout', 'Toad flanders', 'Lethal'],
  },
  {
    date: ['2006', '12', '1'],
    venue: 'Le Batofar',
    city: 'Paris',
    country: 'France',
    bands: ['Hogwash', 'Nothing More', 'The Marxmallows', 'Side effect'],
  },
  {
    date: ['2007', '1', '19'],
    venue: "L'observatoire",
    city: 'Cergy',
    country: 'France',
    bands: ['The Marxmallows', 'Thirty Six Side'],
  },
  {
    date: ['2007', '4', '7'],
    venue: 'Le backstage',
    city: 'Le Mans',
    country: 'France',
    bands: ['Nine eleven', 'Monkey Said', 'Collaps machine'],
  },
  {
    date: ['2007', '4', '14'],
    venue: "L'industrya",
    city: 'Nantes',
    country: 'France',
    bands: ['Jetsex', 'Gravity slaves', "Burst one's side", 'Santa Cruz', 'Trouble everyday'],
  },
  {
    date: ['2007', '5', '8'],
    venue: 'le Batofar',
    city: 'Paris',
    country: 'France',
    bands: ['This is a standoff', 'Big D and the kid table'],
  },
  {
    date: ['2007', '5', '17'],
    venue: 'La casa',
    tour: 'knut tour',
    city: 'Berlin',
    country: 'Germany',
    bands: ['False Friend'],
  },
  {
    date: ['2007', '5', '18'],
    venue: 'B58',
    tour: 'knut tour',
    city: 'Braunschweig',
    country: 'Germany',
    bands: ['False Friend'],
  },
  {
    date: ['2007', '5', '19'],
    venue: 'Dosto',
    tour: 'knut tour',
    city: 'Bernau',
    country: 'Germany',
    bands: ['False Friend'],
  },
  {
    date: ['2007', '5', '22'],
    venue: 'le Batofar',
    city: 'Paris',
    country: 'France',
    bands: ['Another Breath', 'The legacy', "Burst one's side"],
  },
  {
    date: ['2007', '5', '25'],
    venue: 'Le mondo bizarro',
    city: 'Rennes',
    country: 'France',
    bands: ['Nine eleven', 'Baxter'],
  },
  {
    date: ['2007', '5', '26'],
    venue: 'Le mars attack',
    city: 'Angoulème',
    country: 'France',
    bands: ['Nine eleven', 'Mel team plugs'],
  },
  {
    date: ['2007', '6', '2'],
    venue: 'Free edge fest',
    city: 'Chambray les tours',
    country: 'France',
    bands: [
      'Another Breath',
      'Amen râ',
      'Rise and fall',
      'killing the dream',
      'right 4 life',
      'just went black',
      'Trashington DC',
      'Sun power',
    ],
  },
  {
    date: ['2007', '6', '9'],
    venue: 'Le Boul et Bill',
    city: 'St Hilaire',
    country: 'France',
    bands: ['Nine eleven'],
  },
  {
    date: ['2007', '6', '17'],
    venue: 'La maroquinerie',
    city: 'Paris',
    country: 'France',
    bands: ['Strike anywhere', 'Berri Txarrak'],
    flyer: 'flyers/2007_06_17',
  },
  {
    date: ['2007', '6', '21'],
    venue: 'Skate parc',
    city: 'Mery sur oise',
    country: 'France',
    bands: ['Side effect', 'Strike Back', 'Union Jack', 'Spark Gap'],
  },
  {
    date: ['2007', '6', '28'],
    venue: 'La scène bastille',
    city: 'Paris',
    country: 'France',
    bands: ['Straightaway', 'Idiotsincrazy'],
  },
  {
    date: ['2007', '7', '20'],
    venue: 'Le sonic',
    city: 'Lyon',
    country: 'France',
    bands: ['Nine eleven', 'The amsterdam red light district'],
  },
  {
    date: ['2007', '7', '21'],
    venue: 'Le volume',
    city: 'Nice',
    country: 'France',
    bands: ['Nine eleven', 'Chasing Paperboy'],
  },
  {
    date: ['2007', '9', '25'],
    venue: 'Le Klub',
    city: 'Paris',
    country: 'France',
    bands: ['True colors', 'Fired up', 'Get lost'],
  },
  {
    date: ['2007', '11', '16'],
    venue: 'Le café charbon',
    city: 'Nevers',
    country: 'France',
    bands: ['Guerilla poubelle', 'Vulgaires machins'],
    gallery: {
      items: [
        {
          publicId: 'photos/nevers_2007/2.jpg',
        },
        {
          publicId: 'photos/nevers_2007/xxbx050bwqidahflgvii',
        },
        {
          publicId: 'photos/nevers_2007/qjaglwndcgdzhldxdpdf',
        },
        {
          publicId: 'photos/nevers_2007/nevers2.jpg',
        },
        {
          publicId: 'photos/nevers_2007/xxbx050bwqidahflgvii',
        },
        {
          publicId: 'photos/nevers_2007/qjaglwndcgdzhldxdpdf',
        },
        {
          publicId: 'photos/nevers_2007/pnjdr7wxh9i5z6phll8e',
        },
        {
          publicId: 'photos/nevers_2007/t8qjvpujivehysb8lie5',
        },
        {
          publicId: 'photos/nevers_2007/r1iyebb7weksblbj0sdq',
        },
        {
          publicId: 'photos/nevers_2007/p59lipg8o3avdeqcbuid',
        },
      ],
    },
  },
  {
    date: ['2008', '2', '21'],
    venue: 'Le rocher',
    tour: 'European Tour 2008',
    city: 'Paris',
    country: 'France',
    bands: ['Nine eleven', 'Strike Back'],
  },
  {
    date: ['2008', '2', '22'],
    venue: 'The point club',
    tour: 'European Tour 2008',
    city: 'Besigheim',
    country: 'Germany',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '23'],
    venue: 'Diwadlo',
    tour: 'European Tour 2008',
    city: 'Prievidza',
    country: 'Slovakia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '24'],
    venue: 'Irish Pub',
    tour: 'European Tour 2008',
    city: 'Banska Bystrika',
    country: 'Slovakia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '25'],
    venue: 'Garaboncia',
    tour: 'European Tour 2008',
    city: 'Szgeden',
    country: 'Hungary',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '26'],
    venue: 'The Rocktogon',
    tour: 'European Tour 2008',
    city: 'Budapest',
    country: 'Hungary',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '27'],
    venue: 'K-Set Club',
    tour: 'European Tour 2008',
    city: 'Zagreb',
    country: 'Croatia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '28'],
    venue: 'Booka',
    tour: 'European Tour 2008',
    city: 'Rijeka',
    country: 'Croatia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '29'],
    venue: 'Orto Bar',
    tour: 'European Tour 2008',
    city: 'Ljubljana',
    country: 'Slovenia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '2', '30'],
    venue: "L'écurie de l'ilot 13",
    tour: 'European Tour 2008',
    city: 'Genève',
    country: 'Switzerland',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '4', '18'],
    venue: 'La fourmi',
    city: 'Limoge',
    country: 'France',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '4', '19'],
    venue: 'Des lendemains qui chantent',
    city: 'Tulle',
    country: 'France',
    bands: ['Nine eleven', '25 ta life'],
  },
  {
    date: ['2008', '5', '24'],
    venue: 'La scène bastille',
    city: 'Paris',
    country: 'France',
    bands: ['Headchargers'],
  },
  {
    date: ['2008', '6', '21'],
    venue: 'La mécanique ondulatoire',
    city: 'Paris',
    country: 'France',
    bands: ['Frank Turner', 'Bad Chikens', 'For a second'],
  },
  {
    date: ['2008', '6', '27'],
    venue: "L'espace B",
    city: 'Paris',
    country: 'France',
    bands: ['Off your head', 'Noid'],
  },
  {
    date: ['2008', '8', '23'],
    venue: 'Festival la ferme du rock',
    city: 'Pont-Sainte-Maxence',
    country: 'France',
    bands: ['Nada Surf', 'Empyr', 'Tagada Jones'],
  },
  {
    date: ['2008', '10', '24'],
    venue: 'Jukuz',
    tour: 'European Tour 2008 part. 2',
    city: 'Micheldorf',
    country: 'Austria',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '25'],
    venue: 'MKC',
    tour: 'European Tour 2008 part. 2',
    city: 'Zupanja',
    country: 'Croatia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '26'],
    venue: 'Klupce',
    tour: 'European Tour 2008 part. 2',
    city: 'Zrenjanin',
    country: 'Serbia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '27'],
    venue: 'Club Roland Garros',
    tour: 'European Tour 2008 part. 2',
    city: 'Cluj Napocca',
    country: 'Romania',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '28'],
    venue: 'Fire Club',
    tour: 'European Tour 2008 part. 2',
    city: 'Bucarest',
    country: 'Romania',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '29'],
    venue: 'Setup',
    tour: 'European Tour 2008 part. 2',
    city: 'Timisoara',
    country: 'Romania',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '30'],
    venue: 'Maxim club',
    tour: 'European Tour 2008 part. 2',
    city: 'Selencha',
    country: 'Serbia',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '10', '31'],
    venue: 'Capanone',
    tour: 'European Tour 2008 part. 2',
    city: 'Vicenza',
    country: 'Italy',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '11', '1'],
    venue: 'Taurus',
    tour: 'European Tour 2008 part. 2',
    city: 'Turin',
    country: 'Italy',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '11', '2'],
    venue: 'New Bar',
    tour: 'European Tour 2008 part. 2',
    city: 'Nevers',
    country: 'France',
    bands: ['Nine eleven'],
  },
  {
    date: ['2008', '12', '12'],
    venue: "L'espace B",
    city: 'Paris',
    country: 'France',
    bands: ['The living Daylights', 'the fury furyz'],
  },
  {
    date: ['2008', '12', '13'],
    venue: 'Le jardin moderne',
    city: 'Rennes',
    country: 'France',
    bands: ['The living Daylights', 'Ravi', 'Sling 69'],
  },
  {
    date: ['2009', '2', '15'],
    venue: 'Ringside',
    tour: 'UK Tour 2008',
    city: 'Hull',
    country: 'England',
    bands: [],
  },
  {
    date: ['2009', '2', '16'],
    venue: "Harry's bar",
    tour: 'UK Tour 2008',
    city: 'Stoke on trent',
    country: 'England',
    bands: [],
  },
  {
    date: ['2009', '2', '17'],
    venue: "Kat's house",
    tour: 'UK Tour 2008',
    city: 'Swansea',
    country: 'Wales',
    bands: [],
  },
  {
    date: ['2009', '2', '18'],
    venue: 'Club revolution',
    tour: 'UK Tour 2008',
    city: 'Peterborough',
    country: 'England',
    bands: [],
  },
  {
    date: ['2009', '2', '19'],
    venue: 'Old tradex building',
    tour: 'UK Tour 2008',
    city: 'Lincoln',
    country: 'England',
    bands: [],
  },
  {
    date: ['2009', '2', '20'],
    venue: 'Carpenter arms',
    tour: 'UK Tour 2008',
    city: 'Canterburry',
    country: 'England',
    bands: [],
  },
  {
    date: ['2010', '5', '16'],
    venue: 'Alien Fest',
    city: 'Nantes',
    country: 'France',
    bands: ['PO BOX', 'Diego Pallavas', 'Justine', 'Canisquare'],
  },
  {
    date: ['2009', '6', '14'],
    venue: '100 Contest',
    city: 'Cergy',
    country: 'France',
    bands: [],
  },
  {
    date: ['2009', '7', '24'],
    venue: 'Le happy days',
    city: 'Le Mans',
    country: 'France',
    bands: ['Comeback Kid', 'Defeater', 'Alea Jacta est', 'Knock 4 six'],
  },
  {
    date: ['2009', '7', '25'],
    venue: "Glaz'art",
    city: 'Paris',
    country: 'France',
    bands: ['Propagandhi', 'the twisted minds'],
  },
  {
    date: ['2009', '9', '26'],
    venue: 'La chimère',
    city: 'Lille',
    country: 'France',
    bands: ['Fake Off', 'Bedtime for charlie', 'backtime'],
  },
  {
    date: ['2009', '10', '7'],
    venue: 'Le shaka laka',
    city: 'Hazebrouk',
    country: 'France',
    bands: ['Fake Off', 'Strugglin for reason'],
  },
  {
    date: ['2010', '2', '20'],
    venue: 'Club Mosproject',
    tour: 'Russia 2010',
    city: 'Moscou',
    country: 'Russia',
    bands: [],
  },
  {
    date: ['2010', '2', '21'],
    venue: 'Nirvana',
    tour: 'Russia 2010',
    city: 'Ekaterinburg',
    country: 'Russia',
    bands: [],
  },
  {
    date: ['2010', '2', '22'],
    venue: 'Element',
    tour: 'Russia 2010',
    city: 'Ufa',
    country: 'Russia',
    bands: [],
  },
  {
    date: ['2010', '2', '23'],
    venue: 'Bit.com',
    tour: 'Russia 2010',
    city: 'Togliatti',
    country: 'Russia',
    bands: [],
  },
  {
    date: ['2010', '2', '24'],
    venue: 'Hammer club',
    tour: 'Russia 2010',
    city: 'Kolomna',
    country: 'Russia',
    bands: [],
  },
  {
    date: ['2010', '2', '25'],
    venue: 'Osmolon',
    tour: 'Russia 2010',
    city: 'Rostof on don',
    country: 'Russia',
    bands: [],
  },
];

export const concerts: ConcertProps[] = concertsRaw.map((event) => {
  const date = new Date(event.date.join('-'));
  const day = date.getDate();
  const dayString = String(day).padStart(2, '0');
  const monthString = formatEventMonth.format(date);
  return {
    ...event,
    kind: 'concert',
    dateIso: date.toISOString(),
    monthString,
    dayString,
  };
});
